In [1]:
import tensorflow as tf

In [3]:
# matrix로 표현하지 않은 hypothesis
tf.enable_eager_execution()
# data and label
x1 = [ 73.,   93.,   89.,   96.,  73.]
x2 = [ 80.,   88.,   91.,   98.,  66.]
x3 = [ 75.,   93.,  90.,  100.,  70.]
Y  = [152., 185., 180., 196., 142]

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b = tf.Variable(10.)

learning_rate = 0.000001

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print('{} | {:.4f}'.format(i, cost.numpy()))

0 | 5793889.5000
50 | 64291.1484
100 | 715.2902
150 | 9.8462
200 | 2.0152
250 | 1.9252
300 | 1.9210
350 | 1.9177
400 | 1.9145
450 | 1.9114
500 | 1.9081
550 | 1.9050
600 | 1.9018
650 | 1.8986
700 | 1.8955
750 | 1.8923
800 | 1.8892
850 | 1.8861
900 | 1.8829
950 | 1.8798
1000 | 1.8767


In [4]:
import pandas as pd

In [27]:
x1 =  [ 73.,   93.,   89.,   96.,  73.]
x2 = [ 80.,   88.,   91.,   98.,  66.]
x3 = [ 75.,   93.,  90.,  100.,  70.]
Y  = [152., 185., 180., 196., 142]
a = pd.DataFrame([x1, x2, x3, Y])
X = pd.concat([a])
data = X.values.T; data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.]])

In [29]:
y = data[:, -1:]; y

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]])

In [32]:
W = tf.Variable(tf.random_normal([3, 1]));W

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.88102907],
       [-0.355364  ],
       [ 1.3000476 ]], dtype=float32)>

In [35]:
import numpy as np

In [52]:
# matrix로 표현한 hypothesis
tf.enable_eager_execution()
# data and label
data= tf.Variable([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.]])
X = data[:, :-1]
y = data[:, -1:]

# weights
W = tf.Variable(tf.random_normal([3, 1]))
b = tf.Variable(tf.random_normal([1]))

learning_rate = 0.000001

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(hypothesis - y))
    W_grad, b_grad = tape.gradient(cost, [W, b])
    
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print('{} | {:.4f}'.format(i, cost.numpy()))

0 | 103521.2891
50 | 10.9082
100 | 0.6001
150 | 0.5987
200 | 0.5983
250 | 0.5980
300 | 0.5976
350 | 0.5972
400 | 0.5969
450 | 0.5965
500 | 0.5961
550 | 0.5957
600 | 0.5954
650 | 0.5950
700 | 0.5946
750 | 0.5943
800 | 0.5939
850 | 0.5936
900 | 0.5932
950 | 0.5928
1000 | 0.5925
